data_dir: "/var/lib/vector"

sources:
  docker:
    type: docker_logs
    docker_host: unix:///var/run/docker.sock

sinks:
  loki:
    type: loki
    inputs: [docker]
    endpoint: http://loki:3100
    encoding:
      codec: json
    labels:
      job: docker
